import { Policy } from '../shared/types.js';

export const DEFAULT_POLICIES: Policy[] = [
  {
    id: 'POL-PWD-001',
    name: 'Password Security Policy',
    description: 'Mandatory cryptographic standards, entropy requirements, and complexity rules for user and service authentication credentials.',
    category: 'Authentication',
    severity: 'HIGH',
    active: true,
    createdAt: '2026-01-15T09:00:00.000Z',
    updatedAt: '2026-09-01T14:30:00.000Z',
    rules: [
      {
        id: 'RULE-PWD-001',
        policyId: 'POL-PWD-001',
        name: 'Minimum Length Constraint',
        description: 'Passwords must contain at least 12 characters.',
        condition: 'password.length >= 12',
        expectedBehavior: 'Password length must be greater than or equal to 12 UTF-8 characters.',
        severity: 'HIGH',
        remediation: 'Extend password length to a minimum of 12 characters or use a multi-word passphrase.',
        isMandatory: true,
        active: true,
        category: 'Authentication',
      },
      {
        id: 'RULE-PWD-002',
        policyId: 'POL-PWD-001',
        name: 'Uppercase Letter Requirement',
        description: 'Password must contain at least one uppercase letter (A-Z).',
        condition: 'matches(/[A-Z]/)',
        expectedBehavior: 'Password must contain at least one uppercase Latin character [A-Z].',
        severity: 'MEDIUM',
        remediation: 'Add at least one capital letter to your password credential.',
        isMandatory: true,
        active: true,
        category: 'Authentication',
      },
      {
        id: 'RULE-PWD-003',
        policyId: 'POL-PWD-001',
        name: 'Lowercase Letter Requirement',
        description: 'Password must contain at least one lowercase letter (a-z).',
        condition: 'matches(/[a-z]/)',
        expectedBehavior: 'Password must contain at least one lowercase Latin character [a-z].',
        severity: 'MEDIUM',
        remediation: 'Add at least one lowercase letter to your password credential.',
        isMandatory: true,
        active: true,
        category: 'Authentication',
      },
      {
        id: 'RULE-PWD-004',
        policyId: 'POL-PWD-001',
        name: 'Numeric Character Requirement',
        description: 'Password must contain at least one numeric digit (0-9).',
        condition: 'matches(/[0-9]/)',
        expectedBehavior: 'Password must include at least one numerical digit [0-9].',
        severity: 'MEDIUM',
        remediation: 'Include at least one numerical digit in the password.',
        isMandatory: true,
        active: true,
        category: 'Authentication',
      },
      {
        id: 'RULE-PWD-005',
        policyId: 'POL-PWD-001',
        name: 'Special Symbol Requirement',
        description: 'Password must contain at least one special character (!@#$%^&*()_+-=[]{}|;:,.<>?).',
        condition: 'matches(/[^A-Za-z0-9]/)',
        expectedBehavior: 'Password must include at least one non-alphanumeric punctuation or symbol character.',
        severity: 'HIGH',
        remediation: 'Include at least one symbol such as !, @, #, $, or &.',
        isMandatory: true,
        active: true,
        category: 'Authentication',
      },
      {
        id: 'RULE-PWD-006',
        policyId: 'POL-PWD-001',
        name: 'Common Word & Predictable Sequence Blacklist',
        description: 'Password must not contain dictionary words, default phrases ("password", "admin", "welcome"), or trivial numeric sequences ("123456").',
        condition: '!containsBlacklistedWord(password)',
        expectedBehavior: 'Password must avoid predictable patterns, dictionary terms, and default system passwords.',
        severity: 'CRITICAL',
        remediation: 'Avoid obvious words, company names, sequential keystrokes (qwerty), or predictable numbers.',
        isMandatory: true,
        active: true,
        category: 'Authentication',
      },
    ],
  },
  {
    id: 'POL-PII-002',
    name: 'Personal Data Handling (PII) Policy',
    description: 'Governance for detecting and safeguarding Personally Identifiable Information (PII), national identification numbers, financial credentials, and confidential secrets in transmitted payloads.',
    category: 'Data Privacy',
    severity: 'CRITICAL',
    active: true,
    createdAt: '2026-02-10T10:15:00.000Z',
    updatedAt: '2026-08-20T11:00:00.000Z',
    rules: [
      {
        id: 'RULE-PII-001',
        policyId: 'POL-PII-002',
        name: 'Unencrypted National ID / SSN Prohibition',
        description: 'Unmasked Social Security Numbers (SSN: XXX-XX-XXXX) or national identification numbers must never appear in plaintext logs, communications, or public records.',
        condition: '!hasPlaintextSSN(text)',
        expectedBehavior: 'All SSN or National ID instances must be tokenized or cryptographically masked (e.g., ***-**-1234).',
        severity: 'CRITICAL',
        remediation: 'Mask the national identification number or replace it with an opaque surrogate UUID.',
        isMandatory: true,
        active: true,
        category: 'Data Privacy',
      },
      {
        id: 'RULE-PII-002',
        policyId: 'POL-PII-002',
        name: 'Payment Card Number (PAN) Masking',
        description: 'Full credit or debit card primary account numbers (13 to 19 digits) must not be stored or transmitted in plain text without PCI-DSS tokenization.',
        condition: '!hasPlaintextCreditCard(text)',
        expectedBehavior: 'Payment card numbers must be truncated to no more than the last 4 digits (e.g. **** **** **** 4242).',
        severity: 'CRITICAL',
        remediation: 'Remove the full card number and route through a compliant payment vault token.',
        isMandatory: true,
        active: true,
        category: 'Data Privacy',
      },
      {
        id: 'RULE-PII-003',
        policyId: 'POL-PII-002',
        name: 'Embedded Private Keys & API Secrets Leak Prevention',
        description: 'Software API tokens, RSA private keys, AWS access keys, or bearer credentials must never be committed into payload text.',
        condition: '!hasSecretCredentials(text)',
        expectedBehavior: 'Zero secrets, private keys (BEGIN PRIVATE KEY), or cloud provider access keys in payload.',
        severity: 'CRITICAL',
        remediation: 'Immediately revoke leaked keys, store credentials in a secure secrets manager, and remove from the input.',
        isMandatory: true,
        active: true,
        category: 'Data Privacy',
      },
      {
        id: 'RULE-PII-004',
        policyId: 'POL-PII-002',
        name: 'Unconsented Sensitive Health Information (PHI)',
        description: 'Diagnoses, prescription records, or Protected Health Information must have documented patient consent and HIPAA authorization markers.',
        condition: 'hasExplicitConsentWhenHealthDataPresent(text)',
        expectedBehavior: 'Any health diagnosis or biometric data must explicitly reference patient consent and authorized medical processing scope.',
        severity: 'HIGH',
        remediation: 'Include explicit patient consent certification or de-identify medical records pursuant to HIPAA safe harbor.',
        isMandatory: true,
        active: true,
        category: 'Data Privacy',
      },
    ],
  },
  {
    id: 'POL-RET-003',
    name: 'Data Retention & Disposal Policy',
    description: 'Defines regulatory maximum retention durations, audit archive lifecycles, and user right-to-erasure guarantees.',
    category: 'Compliance & Governance',
    severity: 'HIGH',
    active: true,
    createdAt: '2026-03-01T08:00:00.000Z',
    updatedAt: '2026-07-14T16:20:00.000Z',
    rules: [
      {
        id: 'RULE-RET-001',
        policyId: 'POL-RET-003',
        name: 'Financial & Transaction Retention Cap',
        description: 'Customer transaction and billing records must specify a finite retention schedule not exceeding 7 years (84 months). Indefinite or infinite storage is strictly non-compliant.',
        condition: 'retentionSchedule <= 7 years && !isIndefinite',
        expectedBehavior: 'Retention duration must be explicitly stated and capped at a maximum of 7 years / 84 months.',
        severity: 'HIGH',
        remediation: 'Update data lifecycle policy to specify an automated purger capped at 7 years.',
        isMandatory: true,
        active: true,
        category: 'Compliance & Governance',
      },
      {
        id: 'RULE-RET-002',
        policyId: 'POL-RET-003',
        name: 'Telemetry & Web Access Log Maximum TTL',
        description: 'Raw web traffic logs, IP address traces, and session telemetry must have a maximum TTL of 90 days unless irreversibly aggregated.',
        condition: 'telemetryRetentionDays <= 90',
        expectedBehavior: 'Server and IP access logs must be purged or anonymized within 90 days.',
        severity: 'MEDIUM',
        remediation: 'Set web server log retention rotation policy to 90 days maximum.',
        isMandatory: true,
        active: true,
        category: 'Compliance & Governance',
      },
      {
        id: 'RULE-RET-003',
        policyId: 'POL-RET-003',
        name: 'GDPR Right-to-Erasure 30-Day SLA',
        description: 'Customer erasure and account deletion requests must mandate permanent data purging within a 30-day statutory SLA.',
        condition: 'deletionSLA <= 30 days',
        expectedBehavior: 'Data erasure workflows must commit to completion within 30 calendar days of verified request.',
        severity: 'CRITICAL',
        remediation: 'Ensure data deletion procedures stipulate execution within 30 days.',
        isMandatory: true,
        active: true,
        category: 'Compliance & Governance',
      },
    ],
  },
  {
    id: 'POL-ACC-004',
    name: 'Access Control & Least Privilege Policy',
    description: 'Enforces Multi-Factor Authentication (MFA), role-based privilege boundaries, and restrictions on default and shared accounts.',
    category: 'Identity & Access',
    severity: 'HIGH',
    active: true,
    createdAt: '2026-03-20T12:00:00.000Z',
    updatedAt: '2026-08-15T09:45:00.000Z',
    rules: [
      {
        id: 'RULE-ACC-001',
        policyId: 'POL-ACC-004',
        name: 'Privileged Account Multi-Factor Authentication',
        description: 'All system administrator, database admin, and elevated root accounts must require hardware token or authenticator app MFA.',
        condition: 'mfaEnforced == true for elevated roles',
        expectedBehavior: 'Administrative access configurations must state that multi-factor authentication (MFA/2FA) is strictly mandatory.',
        severity: 'CRITICAL',
        remediation: 'Enable mandatory MFA enforcement for all administrator, devops, and database operator credentials.',
        isMandatory: true,
        active: true,
        category: 'Identity & Access',
      },
      {
        id: 'RULE-ACC-002',
        policyId: 'POL-ACC-004',
        name: 'Prohibition of Shared Generic Administrative Accounts',
        description: 'Shared credentials (e.g., "admin/admin", "shared_team", "support_group") are strictly prohibited; each privileged session must attribute to an individual named operator.',
        condition: '!usesSharedCredentials',
        expectedBehavior: 'All accounts must be mapped to distinct individuals; no generic group logins.',
        severity: 'HIGH',
        remediation: 'Decommission generic or shared logins and issue individualized credentials with audit trails.',
        isMandatory: true,
        active: true,
        category: 'Identity & Access',
      },
      {
        id: 'RULE-ACC-003',
        policyId: 'POL-ACC-004',
        name: 'Vendor and Contractor Account Expiration Cap',
        description: 'Temporary third-party vendor, auditor, and external contractor accounts must have explicit expiration dates not exceeding 180 days.',
        condition: 'contractorAccountLifespanDays <= 180',
        expectedBehavior: 'External contractor credentials must include an automatic expiration date within 180 days.',
        severity: 'MEDIUM',
        remediation: 'Configure an account expiration timestamp of 180 days or less on third-party user profiles.',
        isMandatory: true,
        active: true,
        category: 'Identity & Access',
      },
    ],
  },
  {
    id: 'POL-DOC-005',
    name: 'Document & Asset Sharing Policy',
    description: 'Governs document classification tiers, public anonymous link prohibitions, external domain restrictions, and watermarking controls.',
    category: 'Information Security',
    severity: 'HIGH',
    active: true,
    createdAt: '2026-04-05T14:00:00.000Z',
    updatedAt: '2026-09-10T17:00:00.000Z',
    rules: [
      {
        id: 'RULE-DOC-001',
        policyId: 'POL-DOC-005',
        name: 'Confidential Document Public Link Prohibition',
        description: 'Documents marked CONFIDENTIAL, RESTRICTED, or containing customer lists/financials must never be configured with "Anyone with the link can view/edit" access.',
        condition: '!hasPublicLinkForConfidentialDocs',
        expectedBehavior: 'Public anonymous sharing links are strictly forbidden for confidential or proprietary materials.',
        severity: 'CRITICAL',
        remediation: 'Change document access from public link to specific authenticated corporate email addresses only.',
        isMandatory: true,
        active: true,
        category: 'Information Security',
      },
      {
        id: 'RULE-DOC-002',
        policyId: 'POL-DOC-005',
        name: 'Approved Domain Boundary for External Sharing',
        description: 'External file and folder sharing must be restricted to verified business partner domains or require pre-approval.',
        condition: 'sharesOnlyWithApprovedDomains',
        expectedBehavior: 'Sharing destinations must not target free/consumer webmail (e.g., personal @gmail, @yahoo) for company confidential files.',
        severity: 'HIGH',
        remediation: 'Restrict sharing to corporate email addresses of vetted partner organizations.',
        isMandatory: true,
        active: true,
        category: 'Information Security',
      },
      {
        id: 'RULE-DOC-003',
        policyId: 'POL-DOC-005',
        name: 'Bulk Export Protection & Watermark Mandate',
        description: 'Bulk exports of customer records, financial rosters, or employee payroll sheets must enforce encryption or dynamic watermarking with the downloader identity.',
        condition: 'hasExportProtectionOrWatermark',
        expectedBehavior: 'Export policy must specify password protection or personalized audit watermarking for bulk exports.',
        severity: 'MEDIUM',
        remediation: 'Apply encrypted zip protection and dynamic user-email watermarking on downloaded document assets.',
        isMandatory: false,
        active: true,
        category: 'Information Security',
      },
    ],
  },
];
